project:
  type: website
  output-dir: docs

website:
  title: "Replication"

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true

execute:
  eval: false
  echo: true
  warning: false
  message: false
